# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
- openjdk12
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
- bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту ivan150287@gmail.com если сборка упала
notifications:
  email:
    recipients:
    - ivan150287@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:

  global:

  - CODECOV_TOKEN="b8077d79-6f34-4b72-ba69-3316a3397aac"